# Generated by Django 5.1.7 on 2025-03-29 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaPPDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('regulatoria', 'Regulatoria'), ('no_regulatoria', 'No Regulatoria')], max_length=20)),
                ('indicador', models.CharField(max_length=255)),
                ('medio_verificacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=100)),
                ('correo_contacto', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AvanceMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField()),
                ('porcentaje_avance', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('archivo_respaldo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte_ppda.medidappda')),
            ],
        ),
        migrations.AddField(
            model_name='medidappda',
            name='organismo_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte_ppda.organismo'),
        ),
    ]
